services:
     postgres:
          image: postgres:16-alpine
          container_name: to-do-nest-postgres
          restart: unless-stopped
          ports:
               - '${DB_PG_PORT}:5432'
          environment:
               POSTGRES_DB: ${DB_PG_DATABASE}
               POSTGRES_USER: ${DB_PG_USERNAME}
               POSTGRES_PASSWORD: ${DB_PG_PASSWORD}
          volumes:
               - to_do_nest_postgres_data:/var/lib/postgresql/data

     pgadmin:
          image: dpage/pgadmin4:latest
          container_name: pgadmin
          restart: always
          ports:
               - '8085:80'
          environment:
               PGADMIN_DEFAULT_EMAIL: admin@admin.com
               PGADMIN_DEFAULT_PASSWORD: admin123

volumes:
     to_do_nest_postgres_data:
     pgadmin_data:
